### ISSUE TITLE
Old reference to v0.92 in options screen 

### ISSUE THREAD

**Issue by mivsvit** [leeter/WinMTR-refresh#1]
Am running version 0.95 and there is a reference to old v0.92 version when hit the options button in the app:

https://github.com/leeter/WinMTR-refresh/blob/706a38093074826dfcfed69cb9ba9f11a1d18c49/WinMTR.rc#L110

![image](https://user-images.githubusercontent.com/103120230/211818657-335ed356-4f5e-4713-a953-376509bb9808.png)

Perhaps also want to remove the Appnor advert at
https://github.com/leeter/WinMTR-refresh/blob/706a38093074826dfcfed69cb9ba9f11a1d18c49/WinMTR.rc#L109
and
https://github.com/leeter/WinMTR-refresh/blob/706a38093074826dfcfed69cb9ba9f11a1d18c49/WinMTR.rc#L114

**Comment by leeter** [comment]
Do we know what happened to Appnor? I'd rather not completely remove the references to them as they still are primary copyright holders. That said I'll remove the link immediately as it could get squatted on, but these fixes will have to wait for the next release.
