### ISSUE TITLE
A problem that the exe can't shut down before the last packets finishing

### ISSUE THREAD

**Issue by StudentTang** [leeter/WinMTR-refresh#2]
![image](https://user-images.githubusercontent.com/29865920/211999258-34347e90-a5d9-4117-be5a-f58a3aad9f3b.png)
I didn't find why and when it would happen.Maybe the same ports can't be released?

**Comment by StudentTang** [comment]
![image](https://user-images.githubusercontent.com/29865920/211999964-2cd2c63a-c68a-41d4-85dc-9a2c53d62fdd.png)
maybe the local public IP(ipv6).Only close the process in Taskmgr（my systerm win10 22h2  x86-64）

**Comment by StudentTang** [comment]
I have another try,when i open it with administrator privileges,the such host can be stop normally.

**Comment by leeter** [comment]
Please do not run the application with administrative privileges it's not intended to be used that way. I'm aware of the issue and looking into it already. It's a race condition of some sort in the shutdown code. However the likely solution will be adding a forced timer to kill the ICMP handles and return the waits.

**Comment by StudentTang** [comment]
In my computer bug appearing wasn't decide on administrative privileges.Without administrative privileges it still happen occasional（which maybe ICMP packets error），and my firewall didn't set the inbound rules about icmp.

**Comment by leeter** [comment]
The bug happens because the `Timeout` parameter in [`Icmp6SendEcho2 `](https://learn.microsoft.com/en-us/windows/win32/api/icmpapi/nf-icmpapi-icmp6sendecho2) (and the IPv4 equivalent) is ignored when using a callback function. I'm already working on a fix. Running the application as admin should have no effect.

**Comment by leeter** [comment]
Fix done, will be released soon in 0.96
